### ISSUE TITLE
Changing notification settings through the WordPress REST API

### ISSUE THREAD

**Issue by nicucalcea** [OneSignal/OneSignal-WordPress-Plugin#290] opened 2022-03-10 18:39 UTC
**Description:**

I'm publishing content through the WordPress REST API. I would like to toggle the "Send notification on post publish" checkmark on a per-post basis, but I can't see a way to do that through the API.

**Steps to Reproduce Issue:**

1. Upload content through the API (`POST` to `example.com/wp-json/wp/v2/posts`). I'm personally doing it in R.
2. I'm setting the title, description, post status, featured image, etc. in the body of the `POST`.
3. However, I don't know how to customise any of the onesignal settings in the body of the `POST` or in any other programmable way.

**Comment by rgomezp** [comment] 2022-03-10 20:29
Duplicate of https://github.com/OneSignal/OneSignal-WordPress-Plugin/issues/267

**Closed by rgomezp** 2022-03-10 20:29 UTC
