### ISSUE TITLE
Server slow down/website unreachable when new notification is send

### ISSUE THREAD

**Issue by bipalam** [OneSignal/OneSignal-WordPress-Plugin#121] opened 2018-04-19 18:02 UTC
Hi, I am using Wordpress plugin. Whenever I publish new post and send new notification; my website starts to slow down (very slow loading) and finally become unreachable. Website remain unreachable for 5 to 8 minutes and then gradually come back to normal. If I login to my server (WHM) and restart Apache or mySql then website start functioning as normal as soon as I restart.

I tried many things to fix the issue but fails. For e.g. I have tried to improve mysql performance by doing ___ skip-name-resolve and tried every recommendation which script mysqltuner.pl suggest.
When server goes down, I do not see any alarming warning in the log file

I have a good server so I don't think my server will be issue. I am using Dedicated Cloud server from vultr.com, it has **16 GB RAM** and **6 CPU** and **dedicated IP**. Website's SSL is from Comodo.

My website have almost **3 million page-views per month**. 
PHP Version is 7.0 and using PHP FPM and HTTP 2
I am not using any cache plugin or pagespeed module as well as not using any Security plugin such as wp security/wordfence or JetPack

I have **20000+ plus onesignal subscriber**. And my logo/icon which is shown in notification is hosted in Imgur.com

I direly need onesignal but due to the above issue I am not sending any new notification. Please suggest what could be the issue and where to look for.

**Comment by jkasten2** [comment] 2018-04-23 19:46
@bipalam In addition to the increased load of users visiting your site from opening the notification, browsers might be fetching the `OneSignalSDKUpdaterWorker.js.php` and `OneSignalSDKWorker.js.php` files from your server. These are service worker files required to show the push notification and browser may also be refreshing them at this time. I recommend adding trying to add these to files behind some sort of caching or cdn like Cloudflare

**Comment by sknepal** [comment] 2018-05-29 05:13
Have been facing the same issue for months now. Tried mysqltuner but was of no help.

**Comment by jkasten2** [comment] 2018-06-08 01:58
The issue is due to `OneSignalSDKUpdaterWorker.js.php` and `OneSignalSDKWorker.js.php` being fetched by browsers when a notification is received. This can be taxing if you have a large number of subscribers since this is going into PHP instead of being served as a static file from your host. The OneSignal WordPress plugin does not have an option to configure this in the UI however if you can upload some files to the root of your site and can add some javascript to your WordPress template you can use static files.



1. Upload the 3 files noted in [Step 3. Upload OneSignal SDK](https://documentation.onesignal.com/docs/web-push-custom-code-setup#section--span-class-step-step-3-span-upload-onesignal-sdk) of our Custom Code Setup guide.

2. In the WordPress Admin go to OneSignal Push > Advanced Settings  and turn on "Disable OneSignal Initialization".
![image](https://user-images.githubusercontent.com/645861/41134900-a464bb90-6a83-11e8-95b5-692ab6655dda.png)

3. Add the following custom code to your WordPress template 
```html
<script>
  window.OneSignal = window.OneSignal || [];
  window.OneSignal.push(function() {
    OneSignal.SERVICE_WORKER_UPDATER_PATH = "OneSignalSDKUpdaterWorker.js";
    OneSignal.SERVICE_WORKER_PATH = "OneSignalSDKWorker.js";
    OneSignal.SERVICE_WORKER_PARAM = { scope: '/' };
    delete window._oneSignalInitOptions.path
    window.OneSignal.init(window._oneSignalInitOptions);
  });
</script>
```

This should lower CPU and memory usage as users return back to your site however this will be a slow process. Depending on how static files are hosted on your site however this might still not be enough. This is why we recommend using a CDN such a CloudFlare as you can configure this to completely cache these file for you.

If your setting up a new site you can our HTTP option instead of HTTPS as these service worker files will be hosted by os.tc for you.

Also make sure your notification icon is not host on your domain as this will be an extra request to your server when you send a notification.

**Comment by sknepal** [comment] 2018-06-08 05:57
Hi @jkasten2, I did as you said but I can still see the following code on head. This should not be there, right? I have enabled the "Disable OneSignal Initialization" option from the settings. 

     ` OneSignal.push( function() {
        OneSignal.SERVICE_WORKER_UPDATER_PATH = "OneSignalSDKUpdaterWorker.js.php";
        OneSignal.SERVICE_WORKER_PATH = "OneSignalSDKWorker.js.php";
        OneSignal.SERVICE_WORKER_PARAM = { scope: '/' };
        ....`

Site in question: http://bit.ly/2JrqhTw. The code you mentioned has been added towards the end. Can you please look into it?

**Comment by jkasten2** [comment] 2018-06-08 18:57
@sknepal There should still be OneSignal code in `<head>` tag as it will still generated to this to import all the setting you used in the WordPress admin. However the `OneSignal.init` call is removed from `<head>` now so you can change setting and initialize when you want.

I just tested your site and I was prompted and received your welcome notification right away. I visited the `chrome://serviceworker-internals/` page in Chrome afterwards I can see it is correctly using your custom init code as it is showing a `.js` file instead of a `.php` one.
![image](https://user-images.githubusercontent.com/645861/41175769-0373ea04-6b13-11e8-99d4-e6a5135411c7.png)

**Comment by bipalam** [comment] 2018-06-08 19:00
@jkasten2 Last month I tried "custom code" and also installed "wp super cache".  wp-super-cache serve the static html page to my site visitors hence no mysql/database query. 
After set-up what I can see is - The first notification of a day makes my website very very slow BUT the second, third, fourth notification does not slows the website even for a second. 
So everyday my website goes slow on first notification of a day and then runs smoothly no matter how many notification I push after the first one.
Now, if you can suggest something which can fix the first-notification-of-a-day issue, it will be great. I believe cdn may solve the issue completely but it will be a costly fix for me.

I wonder why the first notification of a day makes my site slow while second, third, fourth, ..., notifications gives no issue? Hope you can throw some light on this.

**Comment by jkasten2** [comment] 2018-06-08 19:19
@bipalam The browsers only locally cache the service worker files for 24 hours, regardless of any cache settings. This is why the first notification each day will put extra load on your server.

The best option would be to use a CDN as this will let them cache this for you. CloudFlare as a free plan and is reliable which is why we recommend this one.

**Comment by fatsjohonimahnn** [comment] 2018-07-31 23:33
Closing as this question has been answered sufficiently.

**Closed by fatsjohonimahnn** 2018-07-31 23:33 UTC

**Comment by hexplor** [comment] 2018-08-01 13:14
This seriously SHOULD be placed somewhere visible on the OneSignal website. If you don't use CDN this will literally KILL your server if you have large amount of subscribers. 

@jkasten2 you wrote, "This should lower CPU and memory usage as users return back to your site however this will be a slow process."

Why this will be a slow process ?

Also how it's possible that CloudFlare solves loading of:

```
  OneSignal.SERVICE_WORKER_UPDATER_PATH = "OneSignalSDKUpdaterWorker.js.php";
  OneSignal.SERVICE_WORKER_PATH = "OneSignalSDKWorker.js.php";
```

I believe cloudflare caches static assets, not php files...Or I'am wrong. Thanks in advance for reply.

**Comment by bipalam** [comment] 2018-08-02 03:12
@hexplor Day after @jkasten2 suggest me to go for cloudflare, I did and the issue was solved instantly. Now I have almost 30k subscriber and onesignal no more slows down my server :-)

**Comment by jkasten2** [comment] 2018-08-21 01:46
@henkler We will add a warning about this in a future documentation update to the setup guide

The "Static Service Worker Files" solution take time as it only takes effect for users who come back to your site. Since the service worker file will be downloaded by the browser if it has been 24+ hours since it has check for an update when a notification is received.

CloudFlare can be used to cache any page not just static assets. You'll have to review their setting for these options however

**Comment by trustmedias** [comment] 2018-10-05 17:47
> @henkler We will add a warning about this in a future documentation update to the setup guide
> 
> The "Static Service Worker Files" solution take time as it only takes effect for users who come back to your site. Since the service worker file will be downloaded by the browser if it has been 24+ hours since it has check for an update when a notification is received.
> 
> CloudFlare can be used to cache any page not just static assets. You'll have to review their setting for these options however

Hi,

Thank you for the help your're providing to us. I see I'm not the only one to have this problem.

I'm already on cloudflare so I tried to set something in order to have the concerned files cached, but I'm really not sure I'm doing it the right way. Could you please help me ?

This is what I did :
<img width="837" alt="capture d ecran 2018-10-05 a 19 32 03" src="https://user-images.githubusercontent.com/43890529/46551187-60a8d000-c8d7-11e8-9380-7fac0301f61b.png">

Don't know if it's enough.

Thank you in advance for your help.

Regards,

**Comment by SelimEmre** [comment] 2019-01-12 11:57
> @hexplor Day after @jkasten2 suggest me to go for cloudflare, I did and the issue was solved instantly. Now I have almost 30k subscriber and onesignal no more slows down my server :-)

Hi,, can you share your how to do it ? Thanks. mail: selimemretoy@gmail.com

**Comment by Globerada** [comment] 2019-01-22 15:35
Hi. I am experienced the same problem into a cloud server. When I was using http with more than 10.000 subscribers there wasn't any problem. Now, with https and less than 3000 the apache server collapse after a few seconds and I can't enter into the dashboard of wordpress. The apache or system logs doesn't show nothing special.

How can I fix this? Is using a CDN the unique way?
I am using WPROCKET

**Comment by ibiza69** [comment] 2019-04-01 14:15
Hi to all, I´ve read and read all this post and can´t underestand how to proceed.

For example: if I use cloudflare I have to change our domain nameservers, so means all website with go thru cloudflare 8and we had many problems in the past with this as the site was allwways giving cloudflare error 8conexion), so we had to return to our nameservers. So how could we only attach those files to cloudflare without having to move all the site to their nameservers?

If I use static files hosted in our root directory and place the code at template header, the files still show they are at wp-content/plugins/onesignal instead of in our root directory.

Could anyone explain well with steps to follow to use cloudflare as seems the more stable solution? We only have 3000 suscribers and our site is allways down, with server overloaded, as we have job site and everytime a job offer is published, site goes down, so like 50 times a day... And only because onesignal plugin (wordpress).

Thanks for any help ;)

**Comment by Globerada** [comment] 2020-01-14 17:07
Any news on this? I don't even know why this thread is closed...

**Comment by jkasten2** [comment] 2020-01-14 22:51
@Globerada The solutions are noted in https://github.com/OneSignal/OneSignal-WordPress-Plugin/issues/121#issuecomment-395621413, none of these can automatically be done by this plugin due to limitations of WordPress so we have closed this issue. We have pined this issue however so it is easier to find.

Using a CDN such as CloudFlare will be your best options, since it offloads the ServiceWorker files and it can also be used for other assets on your site once setup.

**Comment by ady001** [comment] 2020-04-09 08:30
Hello,
In this thread there is no **actual detail configuration** guide for caching with **CloudFlare** the php service workers. I've configured a free plan, even ad a page rule pointing to the sdk files and nothing! The site crashes after sending notifications...
The solutions are noted but the CloudFlare one is not very well documented. 
------
using latest onesignal wp plugin
cpanel shared hosting
cloudflare free

**Comment by damzzzz** [comment] 2020-04-17 08:31
Have you tried this in Cloudflare? (Page Rule > Create Rule)
```
*<replacewithdomainname.com>/wp-content/plugins/onesignal-free-web-push-notifications/sdk_files/*
Cache Level: Cache Everything
```

**Comment by rfischmann** [comment] 2020-11-04 12:19
> @hexplor Day after @jkasten2 suggest me to go for cloudflare, I did and the issue was solved instantly. Now I have almost 30k subscriber and onesignal no more slows down my server :-)

How exactly did you set up the Cloudflare Page Rule? It didn't seem to make any difference in my case, server's CPU still going up every time a push is fired.

**Comment by rfischmann** [comment] 2020-11-04 12:22
> Have you tried this in Cloudflare? (Page Rule > Create Rule)
> 
> ```
> *<replacewithdomainname.com>/wp-content/plugins/onesignal-free-web-push-notifications/sdk_files/*
> Cache Level: Cache Everything
> ```

I set up mine like that, didn't make any difference to the issue. Very weird.
