### ISSUE TITLE
Action Message keeps re-adding slashes to escape quotes and displays on the front-end

### ISSUE THREAD

**Issue by jbouganim** [OneSignal/OneSignal-WordPress-Plugin#247] opened 2020-07-23 18:54 UTC
**Description:**
When adding a prompt message with a quote/emoji, slashes are added for each save into options.

**Steps to Reproduce Issue:**

1. Log in to WordPress Admin
1. Visit the OneSignal Config dashboard.
1. Add an action message that includes a single quote/emoji and press Save. 
1. Don't change the message, just press Save again.
Each subsequent save adds a slash from WP to the $_POST vars.
Example
`When there's a run deal, I'd like to be able to send you a notification. Click Allow 👇`

Idea. You can apply `stripslashes` or `stripslashes_deep` to the POST vars.
https://github.com/OneSignal/OneSignal-WordPress-Plugin/blob/master/onesignal-admin.php#L432

**Comment by rgomezp** [comment] 2022-05-25 19:23
Duplicate of #254

**Closed by rgomezp** 2022-05-25 19:23 UTC
