### ISSUE TITLE
User sometimes is not recognized as a subscribed

### ISSUE THREAD

**Issue by pitervergara** [OneSignal/OneSignal-WordPress-Plugin#193] opened 2019-05-16 20:57 UTC
**Description:**

After subscribe to receive noifications, the user sometimes is not recognized as a subscribed user.
On a normal reload after subscribe the error normaly does not occur, but it does happen eventualy.

If I reload the page without cache (CTRL + F5) it fails every time. The bell icon for subscription is show and If I click it I see an error on the console.

By setting up the log level to trace on the console I see the following message every time it fails:

```
[Service Worker Update] Checking service worker version...
[Worker Messenger] The page is not controlled by the service worker yet. Waiting... undefined
[Service Worker Update] Worker did not reply to version query; assuming older version.
[Service Worker Update] Not updating service worker, current active worker state is Bypassed.
```
and the following message is show every time it  works:
```
[Service Worker Update] Checking service worker version...
[Worker Messenger] [Page -> SW] Unicasting 'GetWorkerVersion' to service worker.
[Worker Messenger] Page received message: {command: "GetWorkerVersion", payload: 150703}
[Service Worker Update] Service worker version is current at v150703 (no update required).
```

**Steps to Reproduce Issue:**

My site still on dev environment only, but I see the same messages on console in one of the sites mentioned on the OneSignal Customer Case Studies page: 

1. Go to https://www.evino.com.br/
2. Accept the prompt for notifications
2. Open browser console
3. on the console, run: OneSignal.log.setLevel("TRACE")
4. Close tab
5. Once again, go to https://www.evino.com.br/
6. Note the messages on console showing that the worker is up to date
7. CTRL + F5 
8. Note the messages on console showing that the query for version was not replied

**Anything else:**
I suppouse that it might be related to my page loading too many resources, making it slower and somehow preventing the worker to be ready when the onesignal script runs. This is the current hypotesis with which I'm working. Does it make any sense? Is it possible..? 

The test were runned with:
* Google Chrome Versão 74.0.3729.131 (Versão oficial) 64 bits on Ubuntu Linux 
* Google Chrome Versão 74.0.3729.157 (Versão oficial) 64 bits on Winows 10 

This is the error when I click on subscription icon after CTRL +F5:
```
InvalidStateError: The current environment does not support this operation.
    at Function.getServiceWorkerHref (https://cdn.onesignal.com/sdks/OneSignalPageSDKES6.js?v=150703:1:35788)
    at Ce.<anonymous> (https://cdn.onesignal.com/sdks/OneSignalPageSDKES6.js?v=150703:1:123633)
    at Generator.next (<anonymous>)
    at r (https://cdn.onesignal.com/sdks/OneSignalPageSDKES6.js?v=150703:1:118550)
```

**Comment by rgomezp** [comment] 2019-05-21 00:05
Hello,
I wasn't able to reproduce your issue and everything worked fine for me. What other site are you seeing this on?

**Comment by pitervergara** [comment] 2019-05-21 22:15
Hi, @rgomezp 

I took a few screenshots of a different site (https://www.internethaber.com) in which I experience same behavior.

1) This is what I see when I visit the site for the first time:
![001](https://user-images.githubusercontent.com/4817545/58133912-9f3b9280-7bfb-11e9-9876-8cf804efcdfd.PNG)

2) This is what I see after I click the subscribe button:
![002](https://user-images.githubusercontent.com/4817545/58133984-d27e2180-7bfb-11e9-977b-9cc27d8ae548.PNG)

3) This is what I see when I visit the site for a second time, as a subscribed user. The same happens if I refresh the site by pressing F5 (note that the subscribe button is not showed):
![003](https://user-images.githubusercontent.com/4817545/58134080-1113dc00-7bfc-11e9-92b7-7b907a6bef3a.PNG)

4) This is what I see if I hit CTRL + F5 (note that the subscribe button is enabled again):
![004](https://user-images.githubusercontent.com/4817545/58134113-2983f680-7bfc-11e9-842a-f9a6fc3f555b.PNG)

5) This is what I see if I click on the subscribe button after a CTRL + F5
![005](https://user-images.githubusercontent.com/4817545/58134181-5932fe80-7bfc-11e9-89dc-e854436e86ae.PNG)

**Comment by rgomezp** [comment] 2019-05-22 17:36
I see. This isn't something to be worried about. Simply do not refresh the page.  If the page is hard refreshed bypassing the cache, no service worker will control the page. It doesn't matter if we try to reinstall an existing worker; still no service worker will control the page after installation.

**Comment by pitervergara** [comment] 2019-05-24 16:50
@rgomezp , The thing is that, in my site, this does not happens only when I do a "hard refresh" on the page. The hard refresh was the manner through which I managed to replicate the behaviour the happens eventually with some users (without them having their cache cleaned).
Do you have any ideis on what else (aside from cache) could create this situation in which the Service Worker does not reply to the version query? 

Thanks for your the time, by the way

**Comment by rgomezp** [comment] 2019-05-28 23:09
@pitervergara ,
My pleasure. I can't think of anything off the top of my head. 

Are you receiving lots of reports of this? How are you sure this is a widespread issue across your user-base?

**Comment by pitervergara** [comment] 2019-05-29 11:47
Actually, I don't. I have seen this on the staging environment, with different users and browsers, but my user base for now it's only with a few internal users. 
The site is going live next friday. I'll update this thread with new informations next week, I hope that by closing it. In any case, if I get new reports it will them be easier to debug, considering that my site will be accessible.

Thanks for now!

**Comment by rgomezp** [comment] 2019-05-29 16:20
No problem!

**Comment by pitervergara** [comment] 2019-06-07 17:05
Hello,
The site has been online for a week now and I didn't receive any reports of problems concerning the plugin. I'll close the issue. Thanks for your time again!

**Comment by rgomezp** [comment] 2019-06-07 17:12
@pitervergara no problem!

**Comment by TheMacros** [comment] 2020-01-17 14:01
Hello.
It seems I have the same error on each site where I use OneSignal. For example https://p16.areama.net/en/

**Comment by lamnv5490** [comment] 2020-03-24 10:25
> Hello.
> It seems I have the same error on each site where I use OneSignal. For example https://p16.areama.net/en/

I can see ur error is the same as mine.

@rgomezp what information do u need to reproduct ?

**Comment by tpresing** [comment] 2020-04-14 09:54
It happens to me also. :(

**Comment by rgomezp** [comment] 2020-04-29 20:49
I was able to reproduce the issue. However, this is quite low priority. Note that the next time a user refreshes or visits the page, everything will work fine again. Thanks everyone for your patience

**Comment by ErcinDedeoglu** [comment] 2020-05-15 08:33
![Screenshot_1](https://user-images.githubusercontent.com/6512072/82029573-de31e600-969f-11ea-85ce-98d76c5da74a.png)

I have same problem, but I can't say the cause. Because sometimes it's not giving error sometimes it. Every page refresh, it changes.

**Comment by ErcinDedeoglu** [comment] 2020-05-15 08:51
This issue should be at high priority. Because first time users can't receive prompt. This is shame.

**Comment by atimbang-ROAM** [comment] 2020-05-15 09:39
Currently facing the same issue, would be nice to put some thought into it.

**Comment by DmitrySobolevski** [comment] 2020-05-20 08:28
Also faced with this error :(

**Comment by 11tonytony11** [comment] 2020-06-07 18:19
I am also facing this issue. Some of the users don't get the notification

**Comment by jascaldeira** [comment] 2020-06-16 18:19
Same problem here :(

**Comment by rgomezp** [comment] 2020-06-16 23:20
@TheMacros ,
You have the SDK on a different scope. Please reach out to OneSignal support for assistance.

For everyone else, this is actually a limitation of browsers. If the page is hard refreshed bypassing the cache, no service worker will control the page. It doesn't matter if we try to reinstall an existing worker; still no service worker will control the page after installation.

For these reasons, this is not really an issue with the Wordpress Plugin specifically and I will go ahead and close this issue. I recommend not hard-refreshing

**Closed by rgomezp** 2020-06-16 23:20 UTC
Labels: Reproducible, type: bug

**Comment by dmyers** [comment] 2020-08-12 03:03
Also same problem here. 👎

**Comment by tuananhzippy** [comment] 2020-09-03 06:50
I also encountered the same problem. Hope this error will be fixed soon.

[https://trello-attachments.s3.amazonaws.com/58b3c808430a54d1882da8ce/5f4dafc390485c09fb4645d1/1414x202/d0e3b0218a842e9e25932274d3c7af33/Screen_Shot_2020-08-28_at_2.25.44_PM.png](url)

**Comment by jfishman1** [comment] 2020-09-03 20:34
For this issue, it is best to reach out to support@onesignal.com and provide your OneSignal app id or site url with the code, our support team can identify any issues that may be occurring.

**Comment by ViorelMocanu** [comment] 2020-09-10 14:37
Same issue here...

**Comment by cortinashd** [comment] 2020-09-14 04:30
Buenas noches, tambien tengo el mismo problema alguien a podido solucionar el error ?

**Comment by imdadturi** [comment] 2020-09-17 13:15
same error

**Comment by connectfarm** [comment] 2020-10-10 01:36
same error also
